# Generated by Django 4.2.6 on 2023-10-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0002_profile_about_profile_address_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price Of Photo Session'),
        ),
    ]
