# Generated by Django 4.2.5 on 2024-03-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
