# Generated by Django 4.2.5 on 2024-03-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0008_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
