# Generated by Django 4.2.5 on 2024-03-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0010_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=40)),
                ('work', models.ImageField(upload_to='media/')),
                ('grapher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grapher.profile')),
            ],
        ),
    ]
