# Generated by Django 4.2.5 on 2024-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0011_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Your Image'),
        ),
    ]
