# Generated by Django 4.2.5 on 2024-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='media', verbose_name='Your Image'),
        ),
    ]
