# Generated by Django 4.2.6 on 2024-08-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
